/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import gerenciadormicrofones.DaoMicros;

/**
 *
 * @author MarcosB
 */
public class MainI extends javax.swing.JFrame {
    public static DaoMicros microfones = new DaoMicros();
    private Runnable ble=new Runnable() {
            @Override
            public void run() {
                while(true){
                    update();   
                }
            }
        };;
    public Thread t1 = new Thread(ble);
    /**
     * Creates new form MainI
     */
    final void LOAD(){
        jLabel8.setText("OFF");
        jLabel10.setText("OFF");
        jLabel11.setText("OFF");
        jLabel12.setText("OFF");
        jLabel13.setText("OFF");
        jLabel14.setText("OFF");
        jLabel15.setText("OFF");
        jLabel16.setText("OFF");
        t1.start();
    }
    public MainI() {
        initComponents();
        LOAD();
        
    }   
void update(){
        if(microfones.alterado!=0){
            for(int i=0;i<microfones.getLista().size();i++){
                    setVisible(false);
                    if(microfones.getLista().get(i).getNumero()==1){
                       jLabel8.setText(microfones.getLista().get(i).getNomePessoa());
                       repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==2){
                       jLabel10.setText(microfones.getLista().get(i).getNomePessoa());
                       repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==3){
                        jLabel11.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==4){
                        jLabel12.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==5){
                        jLabel13.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==6){
                        jLabel14.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==7){
                        jLabel15.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    if(microfones.getLista().get(i).getNumero()==8){
                        jLabel16.setText(microfones.getLista().get(i).getNomePessoa());
                        repaint();
                    }
                    microfones.alterado=0;
            }
        setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cor1 = new javax.swing.JPanel();
        cor2 = new javax.swing.JPanel();
        cor3 = new javax.swing.JPanel();
        cor4 = new javax.swing.JPanel();
        cor5 = new javax.swing.JPanel();
        cor6 = new javax.swing.JPanel();
        cor7 = new javax.swing.JPanel();
        cor8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cor9 = new javax.swing.JPanel();
        cor10 = new javax.swing.JPanel();
        cor11 = new javax.swing.JPanel();
        cor12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("      1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 60, -1));

        jLabel2.setText("      2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 60, -1));

        jLabel3.setText("      3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 60, -1));

        jLabel4.setText("      4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 60, -1));

        jLabel5.setText("      5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 60, -1));

        jLabel6.setText("      7");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 60, -1));

        jLabel7.setText("      6");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 66, -1));

        jLabel9.setText("      8");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 60, -1));

        cor1.setBackground(new java.awt.Color(0, 0, 0));
        cor1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor1Layout = new javax.swing.GroupLayout(cor1);
        cor1.setLayout(cor1Layout);
        cor1Layout.setHorizontalGroup(
            cor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor1Layout.setVerticalGroup(
            cor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 510));

        cor2.setBackground(new java.awt.Color(51, 51, 255));
        cor2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor2Layout = new javax.swing.GroupLayout(cor2);
        cor2.setLayout(cor2Layout);
        cor2Layout.setHorizontalGroup(
            cor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor2Layout.setVerticalGroup(
            cor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 510));

        cor3.setBackground(new java.awt.Color(255, 51, 51));
        cor3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor3Layout = new javax.swing.GroupLayout(cor3);
        cor3.setLayout(cor3Layout);
        cor3Layout.setHorizontalGroup(
            cor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor3Layout.setVerticalGroup(
            cor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 60, 510));

        cor4.setBackground(new java.awt.Color(255, 255, 102));
        cor4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor4Layout = new javax.swing.GroupLayout(cor4);
        cor4.setLayout(cor4Layout);
        cor4Layout.setHorizontalGroup(
            cor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor4Layout.setVerticalGroup(
            cor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 60, 510));

        cor5.setBackground(new java.awt.Color(255, 204, 204));
        cor5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor5Layout = new javax.swing.GroupLayout(cor5);
        cor5.setLayout(cor5Layout);
        cor5Layout.setHorizontalGroup(
            cor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor5Layout.setVerticalGroup(
            cor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 510));

        cor6.setBackground(new java.awt.Color(51, 255, 51));
        cor6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor6Layout = new javax.swing.GroupLayout(cor6);
        cor6.setLayout(cor6Layout);
        cor6Layout.setHorizontalGroup(
            cor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        cor6Layout.setVerticalGroup(
            cor6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 510));

        cor7.setBackground(new java.awt.Color(255, 153, 0));
        cor7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor7Layout = new javax.swing.GroupLayout(cor7);
        cor7.setLayout(cor7Layout);
        cor7Layout.setHorizontalGroup(
            cor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor7Layout.setVerticalGroup(
            cor7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 510));

        cor8.setBackground(new java.awt.Color(51, 153, 0));
        cor8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor8Layout = new javax.swing.GroupLayout(cor8);
        cor8.setLayout(cor8Layout);
        cor8Layout.setHorizontalGroup(
            cor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor8Layout.setVerticalGroup(
            cor8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 510));

        jLabel8.setText("?????????");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel10.setText("?????????");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel11.setText("?????????");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        jLabel12.setText("?????????");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, -1, -1));

        jLabel13.setText("?????????");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel14.setText("?????????");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));

        jLabel15.setText("?????????");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        jLabel16.setText("?????????");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel17.setText("      5");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 60, -1));

        jLabel18.setText("      7");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 60, -1));

        jLabel19.setText("      6");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 66, -1));

        jLabel20.setText("      8");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 60, -1));

        cor9.setBackground(new java.awt.Color(255, 204, 204));
        cor9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor9Layout = new javax.swing.GroupLayout(cor9);
        cor9.setLayout(cor9Layout);
        cor9Layout.setHorizontalGroup(
            cor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor9Layout.setVerticalGroup(
            cor9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 510));

        cor10.setBackground(new java.awt.Color(51, 255, 51));
        cor10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor10.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor10Layout = new javax.swing.GroupLayout(cor10);
        cor10.setLayout(cor10Layout);
        cor10Layout.setHorizontalGroup(
            cor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        cor10Layout.setVerticalGroup(
            cor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 510));

        cor11.setBackground(new java.awt.Color(255, 153, 0));
        cor11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor11.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor11Layout = new javax.swing.GroupLayout(cor11);
        cor11.setLayout(cor11Layout);
        cor11Layout.setHorizontalGroup(
            cor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor11Layout.setVerticalGroup(
            cor11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 510));

        cor12.setBackground(new java.awt.Color(51, 153, 0));
        cor12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cor12.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cor12Layout = new javax.swing.GroupLayout(cor12);
        cor12.setLayout(cor12Layout);
        cor12Layout.setHorizontalGroup(
            cor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        cor12Layout.setVerticalGroup(
            cor12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        getContentPane().add(cor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 510));

        jLabel21.setText("?????????");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel22.setText("?????????");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));

        jLabel23.setText("?????????");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        jLabel24.setText("?????????");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cor1;
    private javax.swing.JPanel cor10;
    private javax.swing.JPanel cor11;
    private javax.swing.JPanel cor12;
    private javax.swing.JPanel cor2;
    private javax.swing.JPanel cor3;
    private javax.swing.JPanel cor4;
    private javax.swing.JPanel cor5;
    private javax.swing.JPanel cor6;
    private javax.swing.JPanel cor7;
    private javax.swing.JPanel cor8;
    private javax.swing.JPanel cor9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
